### ISSUE TITLE
Update contribution wiki page

### ISSUE THREAD

**Issue by geospatialem** [maptime/map-accessibility-guidelines#13]
Provide a more detailed contribution guide in the wiki (re: [a recent comment](https://github.com/maptime/map-accessibility-guidelines/issues/12#issuecomment-149094431)). :+1:

**Comment by geospatialem** [comment]
Updated the [How to Contribute](../wiki/How-to-Contribute/4f5fc26d5d69cb9c3f829b04df0b8c23f73c8977) wiki page.

**Comment by neuhausr** [comment]
I think this is much clearer, thanks!
